### ISSUE TITLE
Rotate Picture, Right arrow 

### ISSUE THREAD

**Issue by EricBuchinger** [htl-leonding/2016_3CHIF_Photoprofis#3]
Rotate the picture, if it's vertical and it should be horizontal, then display horizontal.
Implement more arrows, two for back and forward, and two for next folder and previous folder and change the picture with the keyboard.

This has to be fixed until 14.4.2016

**Comment by kajicjosip** [comment]
Könnte ich ich 3-4 Tage mehr bekommen, weil Java-Test am Dienstag ist?
Also alles bis auf die den Teil mit den Ordner schaff ich bis zum 10.April

**Comment by kajicjosip** [comment]
Also alles bis auf die den Teil mit den Ordner schaff ich bis zum 10.Mai
